# Generated by Django 3.0.4 on 2020-04-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=30)),
                ('release', models.DateField()),
                ('hero', models.CharField(max_length=30)),
                ('herione', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('movie', 'movie'), ('flix', 'netflix'), ('prime', 'amazon prime'), ('hotstar', 'hotstar')], db_column='Show Type', max_length=30)),
            ],
        ),
    ]
