# Generated by Django 3.0.4 on 2020-04-26 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ModelFormsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedb',
            name='points',
            field=models.IntegerField(db_column='Rating', default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moviedb',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('flix', 'netflix'), ('prime', 'amazon prime'), ('hotstar', 'hotstar')], db_column='Show_Type', max_length=30),
        ),
    ]
