# Generated by Django 3.0.4 on 2020-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0002_auto_20200403_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Student Name', max_length=30)),
                ('dept', models.CharField(choices=[('ME', 'Mechanical'), ('ECE', 'Electronics'), ('EE', 'Electrical')], db_column='Department', max_length=30)),
                ('roll', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Posting Date',
            new_name='PostingDate',
        ),
        migrations.AlterField(
            model_name='job',
            name='PostingDate',
            field=models.DateField(db_column='Posting Date'),
        ),
    ]
